.PHONY: clean All

All:
	@echo "----------Building project:[ Rorelse - Debug ]----------"
	@cd "Rorelse" && "$(MAKE)" -f  "Rorelse.mk" && "$(MAKE)" -f  "Rorelse.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Rorelse - Debug ]----------"
	@cd "Rorelse" && "$(MAKE)" -f  "Rorelse.mk" clean
