.PHONY: clean All

All:
	@echo "----------Building project:[ Periferienhet - Debug ]----------"
	@cd "Periferienhet" && "$(MAKE)" -f  "Periferienhet.mk" && "$(MAKE)" -f  "Periferienhet.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Periferienhet - Debug ]----------"
	@cd "Periferienhet" && "$(MAKE)" -f  "Periferienhet.mk" clean
