.PHONY: clean All

All:
	@echo "----------Building project:[ Centralenhet - Debug ]----------"
	@cd "Centralenhet" && "$(MAKE)" -f  "Centralenhet.mk" && "$(MAKE)" -f  "Centralenhet.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Centralenhet - Debug ]----------"
	@cd "Centralenhet" && "$(MAKE)" -f  "Centralenhet.mk" clean
